export const DEFAULT_GLOSSARY: string[] = [
  "CrowdStrike",
  "CrowdStrike Falcon",
  "Falcon Insight",
  "SentinelOne",
  "Microsoft Defender for Endpoint",
  "Sophos Intercept X",
  "Trend Micro",
  "VMware Carbon Black",
  "Cortex XDR",
  "Trellix",
  "Wazuh",
  "ESET",
  "Elastic Defend",
  "Splunk",
  "QRadar",
  "Elastic",
  "Microsoft Sentinel",
  "Palo Alto Networks",
  "Fortinet",
  "Check Point",
  "Cisco Secure",
  "Zscaler",
  "Okta",
  "Rapid7",
  "Tenable",
  "Qualys",
  "Darktrace",
  "Vectra AI",
  "Cybereason",
  "Mandiant",
  "Snort",
  "Suricata",
  "Zeek",
  "MITRE ATT&CK",
  "Sigma",
  "YARA",
  "Threat Hunting",
  "SOC",
  "SIEM",
  "SOAR",
  "EDR",
  "XDR",
  "MDR",
  "NDR",
  "Zero Trust",
  "Phishing",
  "Ransomware",
  "Malware",
  "Endpoint",
  "Firewall",
]
