export const DEFAULT_GLOSSARY: string[] = [
  "AbuseIPDB",
  "Active Directory",
  "Advanced Persistent Threat",
  "Akamai",
  "AlienVault",
  "Allowlist",
  "AnyDesk",
  "APT",
  "Arctic Wolf",
  "Attack Surface Management",
  "Auth0",
  "AWS",
  "AWS CloudTrail",
  "AWS GuardDuty",
  "AWS IAM",
  "AWS Security Hub",
  "Azure",
  "Azure AD",
  "Azure Active Directory",
  "Azure Defender",
  "Azure Sentinel",
  "Barracuda",
  "Bastion Host",
  "BeyondTrust",
  "Bitdefender",
  "Bitsight",
  "BlackBerry Cylance",
  "Botnet",
  "Brute Force",
  "Burp Suite",
  "CASB",
  "Checkpoint",
  "CISA",
  "Cisco Duo",
  "Cisco Secure",
  "CIS Controls",
  "Cloud Access Security Broker",
  "Cloud Armor",
  "Cloud Detection and Response",
  "Cloud Security",
  "Cloud SIEM",
  "CNAPP",
  "Cobalt Strike",
  "Common Vulnerabilities and Exposures",
  "Compromise Assessment",
  "Containment",
  "CrowdStrike Identity Protection",
  "CrowdStrike",
  "CrowdStrike Falcon",
  "CSIRT",
  "CyberArk",
  "Cyber Kill Chain",
  "Cylance",
  "DDoS",
  "Data Exfiltration",
  "Data Loss Prevention",
  "Defender for Cloud",
  "Defender XDR",
  "Digital Forensics and Incident Response",
  "DLP",
  "DNS Filtering",
  "Domain Controller",
  "EDL",
  "Email Gateway",
  "Entra ID",
  "Endpoint Detection and Response",
  "Enterprise Mobility Management",
  "Escalation of Privilege",
  "EternalBlue",
  "Exabeam",
  "Exploit",
  "Extended Detection and Response",
  "Falcon Complete",
  "Falcon Insight",
  "Firewall de nueva generacion",
  "Firewall",
  "Forensics",
  "FortiAnalyzer",
  "FortiAuthenticator",
  "FortiEDR",
  "FortiGate",
  "FortiManager",
  "FortiSIEM",
  "FortiSOAR",
  "Fortinet",
  "Forescout",
  "FQDN",
  "GCP",
  "GitGuardian",
  "Google Chronicle",
  "Google Cloud",
  "Google SecOps",
  "Graylog",
  "Guardicore",
  "HashiCorp Vault",
  "HIDS",
  "Honeypot",
  "Horizon3.ai",
  "Huntress",
  "IAM",
  "IBM QRadar",
  "ICS",
  "IDS",
  "Indicator of Compromise",
  "Indicator of Attack",
  "Incident Response",
  "Infoblox",
  "Inline Malware Prevention",
  "IOC",
  "IOA",
  "IP Reputation",
  "IPS",
  "ISAC",
  "Ivanti",
  "Jamf Protect",
  "Jump Server",
  "Kaspersky",
  "Kill Chain",
  "KnowBe4",
  "KQL",
  "LAPS",
  "Lateral Movement",
  "LDAP",
  "Least Privilege",
  "Log Management",
  "LogRhythm",
  "LOLBin",
  "Living off the Land",
  "MFA",
  "SentinelOne",
  "Managed Detection and Response",
  "Microsoft Defender",
  "Microsoft Defender for Endpoint",
  "Microsoft Defender for Identity",
  "Microsoft Defender for Cloud Apps",
  "Microsoft Entra",
  "Microsoft Purview",
  "Mimikatz",
  "MITRE",
  "Sophos Intercept X",
  "Mobile Device Management",
  "MSSP",
  "NAC",
  "NDR",
  "Network Access Control",
  "Network Detection and Response",
  "Network Segmentation",
  "NGFW",
  "NIST",
  "Nmap",
  "Okta Verify",
  "Trend Micro",
  "One Identity",
  "OpenCTI",
  "OpenVAS",
  "OSINT",
  "PAM",
  "Palo Alto",
  "Palo Alto Cortex",
  "Palo Alto Networks",
  "Palo Alto Prisma",
  "Pass the Hash",
  "Password Spray",
  "Penetration Testing",
  "Ping Identity",
  "Playbook",
  "Proofpoint",
  "Prisma Access",
  "Prisma Cloud",
  "Privilege Escalation",
  "ProxyShell",
  "ProxyLogon",
  "Purple Team",
  "QRadar",
  "Qualys VMDR",
  "RBA",
  "RBAC",
  "RDP",
  "Red Team",
  "Remote Monitoring and Management",
  "Remediation",
  "Responder",
  "Risk-Based Alerting",
  "Role Based Access Control",
  "RMM",
  "RSA NetWitness",
  "S1",
  "SAML",
  "SASE",
  "SCADA",
  "Secure Access Service Edge",
  "Security Copilot",
  "Security Information and Event Management",
  "Security Operations Center",
  "Security Orchestration Automation and Response",
  "Sentinel",
  "Service Account",
  "Shadow IT",
  "Sigma Rule",
  "SIEM",
  "Skykick",
  "SMB",
  "Snort",
  "SOAR",
  "SOC",
  "SOC analyst",
  "SOC Prime",
  "SOCaaS",
  "Soft Token",
  "Sophos",
  "Sourcefire",
  "SpamTitan",
  "Splunk ES",
  "Splunk Enterprise Security",
  "Spoofing",
  "SQL Injection",
  "SSE",
  "SSO",
  "Sudo",
  "Suricata",
  "Sysmon",
  "TACACS",
  "Tanium",
  "TAP",
  "Tenable.io",
  "Tenable.sc",
  "TheHive",
  "Threat Actor",
  "Threat Hunting",
  "Threat Intelligence",
  "Tines",
  "Token Theft",
  "TOR",
  "TrapX",
  "Triaging",
  "TTP",
  "UEBA",
  "Unit 42",
  "User and Entity Behavior Analytics",
  "UTA",
  "VPN",
  "Vulnerability Assessment",
  "WAF",
  "VMware Carbon Black",
  "VMware Workspace ONE",
  "WatchGuard",
  "Web Application Firewall",
  "Whitelist",
  "Windows Event Forwarding",
  "Windows Hello for Business",
  "WireShark",
  "XDR",
  "XSOAR",
  "YubiKey",
  "Zero Day",
  "Zero Trust Network Access",
  "ZTNA",
  "Cortex XDR",
  "Trellix",
  "Wazuh",
  "ESET",
  "Elastic Defend",
  "Splunk",
  "QRadar",
  "Elastic",
  "Microsoft Sentinel",
  "Elastic Security",
  "Elastic Agent",
  "Elastic Endpoint",
  "Check Point",
  "Zscaler",
  "Okta",
  "Rapid7",
  "Rapid7 InsightIDR",
  "Rapid7 InsightVM",
  "Tenable",
  "Qualys",
  "Darktrace",
  "Vectra AI",
  "Cybereason",
  "Mandiant",
  "Zeek",
  "MITRE ATT&CK",
  "Sigma",
  "YARA",
  "YARA-L",
  "EDR",
  "MDR",
  "Zero Trust",
  "Phishing",
  "Spear Phishing",
  "Business Email Compromise",
  "BEC",
  "Ransomware",
  "Malware",
  "Spyware",
  "Adware",
  "Rootkit",
  "Trojan",
  "Worm",
  "Endpoint",
  "Endpoint Protection",
  "Endpoint Security",
]
